/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jdbc.main;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Jareth Baur
 */
public class AddNewPeripheral extends javax.swing.JFrame {

    private static final String URL = "jdbc:mysql://localhost:3306/oop_jdbc";

    /**
     * Creates new form AddNewPeripheral
     */
    public AddNewPeripheral() {
        initComponents();
    }

    private static Connection connect() {
        try {
            return DriverManager.getConnection(URL);
        } catch (SQLException e) {

            System.out.println("Error connecting to the database: " + e.getMessage());
            throw new RuntimeException("Database connection error", e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnForCreatingAStudent = new javax.swing.JButton();
        btnForCancel = new javax.swing.JButton();
        labelForName = new javax.swing.JLabel();
        labelForLastName = new javax.swing.JLabel();
        txtfieldForName = new javax.swing.JTextField();
        txtfieldForType = new javax.swing.JTextField();
        labelForID = new javax.swing.JLabel();
        txtfieldForID = new javax.swing.JTextField();
        labelForAddress = new javax.swing.JLabel();
        txtfieldForAssigned = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnForCreatingAStudent.setBackground(new java.awt.Color(204, 204, 204));
        btnForCreatingAStudent.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnForCreatingAStudent.setForeground(new java.awt.Color(0, 204, 0));
        btnForCreatingAStudent.setText("Create Peripheral");
        btnForCreatingAStudent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnForCreatingAStudent.setMaximumSize(new java.awt.Dimension(27, 23));
        btnForCreatingAStudent.setMinimumSize(new java.awt.Dimension(27, 23));
        btnForCreatingAStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForCreatingAStudentActionPerformed(evt);
            }
        });

        btnForCancel.setBackground(new java.awt.Color(204, 204, 204));
        btnForCancel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnForCancel.setForeground(new java.awt.Color(255, 0, 51));
        btnForCancel.setText("Cancel");
        btnForCancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnForCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForCancelActionPerformed(evt);
            }
        });

        labelForName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelForName.setForeground(new java.awt.Color(102, 102, 102));
        labelForName.setText("Name:");

        labelForLastName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelForLastName.setForeground(new java.awt.Color(102, 102, 102));
        labelForLastName.setText("Type:");

        txtfieldForName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldForNameActionPerformed(evt);
            }
        });

        txtfieldForType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldForTypeActionPerformed(evt);
            }
        });

        labelForID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelForID.setForeground(new java.awt.Color(102, 102, 102));
        labelForID.setText("Peripheral ID:");

        txtfieldForID.setEditable(false);
        txtfieldForID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtfieldForIDMouseClicked(evt);
            }
        });
        txtfieldForID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldForIDActionPerformed(evt);
            }
        });
        txtfieldForID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfieldForIDKeyTyped(evt);
            }
        });

        labelForAddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelForAddress.setForeground(new java.awt.Color(102, 102, 102));
        labelForAddress.setText("Assigned:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelForAddress)
                            .addComponent(labelForLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfieldForType, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(txtfieldForAssigned)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelForID)
                            .addComponent(labelForName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfieldForName, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(txtfieldForID))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnForCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnForCreatingAStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelForID)
                    .addComponent(txtfieldForID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelForName)
                    .addComponent(txtfieldForName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelForLastName)
                    .addComponent(txtfieldForType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelForAddress)
                    .addComponent(txtfieldForAssigned, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnForCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnForCreatingAStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnForCreatingAStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForCreatingAStudentActionPerformed
        String insertSQL = "INSERT INTO peripheral (name, type, assigned) VALUES (?, ?, ?)";
        try (Connection connection = connect(); PreparedStatement statement = connection.prepareStatement(insertSQL)) {
            statement.setString(1, txtfieldForName.getText());
            statement.setString(2, txtfieldForType.getText());
            statement.setString(3, txtfieldForAssigned.getText());
            if (txtfieldForName.getText().isBlank() || txtfieldForType.getText().isBlank() || !MainJFrame.isAssignedTrue(txtfieldForAssigned.getText())) {
                JOptionPane.showMessageDialog(null, "There was an error creating a record.");
                dispose();
            } else {
                statement.executeUpdate();
                JOptionPane.showMessageDialog(null, "Record created successfully.");
                MainJFrame.resetEmployeeID();
                MainJFrame.resetPeripheralID();
                MainJFrame.refreshTable();
                dispose();
            }
        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnForCreatingAStudentActionPerformed

    private void btnForCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnForCancelActionPerformed

    private void txtfieldForNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldForNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldForNameActionPerformed

    private void txtfieldForTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldForTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldForTypeActionPerformed

    private void txtfieldForIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfieldForIDMouseClicked
        JOptionPane.showMessageDialog(null, "Student ID cannot be modified.");
    }//GEN-LAST:event_txtfieldForIDMouseClicked

    private void txtfieldForIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldForIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldForIDActionPerformed

    private void txtfieldForIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfieldForIDKeyTyped
        JOptionPane.showMessageDialog(null, "Student ID cannot be modified.");
    }//GEN-LAST:event_txtfieldForIDKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewPeripheral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AddNewPeripheral().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnForCancel;
    private javax.swing.JButton btnForCreatingAStudent;
    private javax.swing.JLabel labelForAddress;
    private javax.swing.JLabel labelForID;
    private javax.swing.JLabel labelForLastName;
    private javax.swing.JLabel labelForName;
    private javax.swing.JTextField txtfieldForAssigned;
    private javax.swing.JTextField txtfieldForID;
    private javax.swing.JTextField txtfieldForName;
    private javax.swing.JTextField txtfieldForType;
    // End of variables declaration//GEN-END:variables
}
