/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jdbc.main;

import java.sql.*;
import javax.swing.*;

/**
 * @since December 18, 2023
 * @author Jareth Baur
 */
public class CreateFrameForm extends javax.swing.JFrame {

    private static final String URL = "jdbc:mysql://localhost:3306/oop_jdbc";

    /**
     * Creates new form CreateFrameForm
     */
    public CreateFrameForm() {
        initComponents();
    }

    private static Connection connect() {
        try {
            return DriverManager.getConnection(URL);
        } catch (SQLException e) {

            System.out.println("Error connecting to the database: " + e.getMessage());
            throw new RuntimeException("Database connection error", e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelForID = new javax.swing.JLabel();
        txtfieldForID = new javax.swing.JTextField();
        labelForAddress = new javax.swing.JLabel();
        txtfieldForAddress = new javax.swing.JTextField();
        btnForCreatingAStudent = new javax.swing.JButton();
        btnForCancel = new javax.swing.JButton();
        labelForFirstName = new javax.swing.JLabel();
        labelForLastName = new javax.swing.JLabel();
        txtfieldForFirstName = new javax.swing.JTextField();
        txtfieldForLastName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelForID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelForID.setForeground(new java.awt.Color(102, 102, 102));
        labelForID.setText("Employee ID:");

        txtfieldForID.setEditable(false);
        txtfieldForID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtfieldForIDMouseClicked(evt);
            }
        });
        txtfieldForID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldForIDActionPerformed(evt);
            }
        });
        txtfieldForID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfieldForIDKeyTyped(evt);
            }
        });

        labelForAddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelForAddress.setForeground(new java.awt.Color(102, 102, 102));
        labelForAddress.setText("Address:");

        txtfieldForAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldForAddressActionPerformed(evt);
            }
        });

        btnForCreatingAStudent.setBackground(new java.awt.Color(204, 204, 204));
        btnForCreatingAStudent.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnForCreatingAStudent.setForeground(new java.awt.Color(0, 204, 0));
        btnForCreatingAStudent.setText("Create Employee");
        btnForCreatingAStudent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnForCreatingAStudent.setMaximumSize(new java.awt.Dimension(27, 23));
        btnForCreatingAStudent.setMinimumSize(new java.awt.Dimension(27, 23));
        btnForCreatingAStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForCreatingAStudentActionPerformed(evt);
            }
        });

        btnForCancel.setBackground(new java.awt.Color(204, 204, 204));
        btnForCancel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnForCancel.setForeground(new java.awt.Color(255, 0, 51));
        btnForCancel.setText("Cancel");
        btnForCancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnForCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForCancelActionPerformed(evt);
            }
        });

        labelForFirstName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelForFirstName.setForeground(new java.awt.Color(102, 102, 102));
        labelForFirstName.setText("First Name:");

        labelForLastName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelForLastName.setForeground(new java.awt.Color(102, 102, 102));
        labelForLastName.setText("Last Name:");

        txtfieldForFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldForFirstNameActionPerformed(evt);
            }
        });

        txtfieldForLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldForLastNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnForCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(btnForCreatingAStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelForID)
                                    .addComponent(labelForFirstName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtfieldForFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                    .addComponent(txtfieldForID)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelForLastName)
                                    .addComponent(labelForAddress))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtfieldForLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                    .addComponent(txtfieldForAddress))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelForID)
                    .addComponent(txtfieldForID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelForFirstName)
                    .addComponent(txtfieldForFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelForLastName)
                    .addComponent(txtfieldForLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelForAddress)
                    .addComponent(txtfieldForAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnForCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(btnForCreatingAStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(314, 202));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtfieldForIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldForIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldForIDActionPerformed

    private void txtfieldForAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldForAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldForAddressActionPerformed

    private void btnForCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnForCancelActionPerformed

    private void txtfieldForFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldForFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldForFirstNameActionPerformed

    private void txtfieldForLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldForLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldForLastNameActionPerformed

    private void btnForCreatingAStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForCreatingAStudentActionPerformed
        String insertSQL = "INSERT INTO employee (firstname, lastname, address) VALUES (?, ?, ?)";
        try (Connection connection = connect(); PreparedStatement statement = connection.prepareStatement(insertSQL)) {
            statement.setString(1, txtfieldForFirstName.getText());
            statement.setString(2, txtfieldForLastName.getText());
            statement.setString(3, txtfieldForAddress.getText());
            if (txtfieldForFirstName.getText().isBlank() || txtfieldForLastName.getText().isBlank() || txtfieldForAddress.getText().isBlank()) {
                JOptionPane.showMessageDialog(null, "There was an error creating a record.");
            } else {
                statement.executeUpdate();
                JOptionPane.showMessageDialog(null, "Record created successfully.");
                MainJFrame.refreshTable();
                dispose();
            }
        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnForCreatingAStudentActionPerformed

    private void txtfieldForIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfieldForIDMouseClicked
        JOptionPane.showMessageDialog(null, "Employee ID cannot be modified.");
    }//GEN-LAST:event_txtfieldForIDMouseClicked

    private void txtfieldForIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfieldForIDKeyTyped
        JOptionPane.showMessageDialog(null, "Employee ID cannot be modified.");
    }//GEN-LAST:event_txtfieldForIDKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new CreateFrameForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnForCancel;
    private javax.swing.JButton btnForCreatingAStudent;
    private javax.swing.JLabel labelForAddress;
    private javax.swing.JLabel labelForFirstName;
    private javax.swing.JLabel labelForID;
    private javax.swing.JLabel labelForLastName;
    private javax.swing.JTextField txtfieldForAddress;
    private javax.swing.JTextField txtfieldForFirstName;
    private javax.swing.JTextField txtfieldForID;
    private javax.swing.JTextField txtfieldForLastName;
    // End of variables declaration//GEN-END:variables
}
